import { useState } from "react";
import { Form } from "./form";
import { Calander } from "./calander";
import { AddEvent } from "./addEvent";

// בס"ד
export const Main = () => {
  const [flag, steFlag] = useState(false)
  const [counter, setCounter] = useState(parseInt(window.localStorage.getItem('counter')));
  const [name, setName] = useState("לוח שנה");
  const [font, setFont] = useState();
  const [backRound, setBackRound] = useState();
  const [basicCalender, setBasicCalender] = useState({
    Mounths: [
      {
        name: "תשרי",
        num: "ספטמבר-אוקטובר",
        Days: [
          {
            name: "א",
            num: "23",
            dayOfWeek: 3,
            events: [{ type: "🍎", text: "א דראש השנה" }],
          },
          {
            name: "ב",
            num: "24",
            dayOfWeek: 4,
            events: [{ type: "🍎", text: "ב דראש השנה" }],
          },
          {
            name: "ג",
            num: "25",
            dayOfWeek: 5,
            events: [{ type: "❎", text: "צום גדליה" }],
          },
          { name: "ד", num: "26", dayOfWeek: 6, events: [] },
          { name: "ה", num: "27", dayOfWeek: 7, events: [] },
          { name: "ו", num: "28", dayOfWeek: 1, events: [] },
          { name: "ח", num: "29", dayOfWeek: 3, events: [] },
          { name: "ז", num: "30", dayOfWeek: 2, events: [] },
          { name: "ט", num: "01", dayOfWeek: 4, events: [] },
          {
            name: "י",
            num: "02",
            dayOfWeek: 5,
            events: [{ type: "❎", text: "יום הכיפורים" }],
          },
          { name: "יא", num: "03", dayOfWeek: 6, events: [] },
          { name: "יב", num: "04", dayOfWeek: 7, events: [] },
          { name: "יג", num: "05", dayOfWeek: 1, events: [] },
          { name: "יד", num: "06", dayOfWeek: 2, events: [] },
          {
            name: "טו",
            num: "07",
            dayOfWeek: 3,
            events: [{ type: "🍋", text: "יום טוב סוכות" }],
          },
          {
            name: "טז",
            num: "08",
            dayOfWeek: 4,
            events: [{ type: "🍋", text: "א דחול המועד" }],
          },
          {
            name: "יז",
            num: "09",
            dayOfWeek: 5,
            events: [{ type: "🍋", text: "ב דחול המועד" }],
          },
          {
            name: "יח",
            num: "10",
            dayOfWeek: 6,
            events: [{ type: "🍋", text: "ג דחול המועד" }],
          },
          {
            name: "יט",
            num: "11",
            dayOfWeek: 7,
            events: [{ type: "🍋", text: "ד דחול המועד" }],
          },
          {
            name: "כ",
            num: "12",
            dayOfWeek: 1,
            events: [{ type: "🍋", text: "ה דחול המועד" }],
          },
          {
            name: "כא",
            num: "13",
            dayOfWeek: 2,
            events: [{ type: "🌿", text: "הושענא רבא" }],
          },
          {
            name: "כב",
            num: "14",
            dayOfWeek: 3,
            events: [{ type: "📖", text: "שמיני עצרת ושמחת תורה" }],
          },
          { name: "כג", num: "15", dayOfWeek: 4, events: [] },
          { name: "כד", num: "16", dayOfWeek: 5, events: [] },
          { name: "כה", num: "17", dayOfWeek: 6, events: [] },
          { name: "כו", num: "18", dayOfWeek: 7, events: [] },
          { name: "כז", num: "19", dayOfWeek: 1, events: [] },
          { name: "כח", num: "20", dayOfWeek: 2, events: [] },
          { name: "כט", num: "21", dayOfWeek: 3, events: [] },
          { name: "ל", num: "22", dayOfWeek: 4, events: [] },
        ],
      },

      {
        name: "חשוון",
        num: "אוקטובר-נובמבר",
        Days: [
          { name: "א", num: "23", dayOfWeek: 5, events: [] },
          { name: "ב", num: "24", dayOfWeek: 6, events: [] },
          { name: "ג", num: "25", dayOfWeek: 7, events: [] },
          { name: "ד", num: "26", dayOfWeek: 1, events: [] },
          { name: "ה", num: "27", dayOfWeek: 2, events: [] },
          { name: "ו", num: "28", dayOfWeek: 3, events: [] },
          { name: "ז", num: "29", dayOfWeek: 4, events: [] },
          { name: "ח", num: "30", dayOfWeek: 5, events: [] },
          { name: "ט", num: "31", dayOfWeek: 6, events: [] },
          { name: "י", num: "01", dayOfWeek: 7, events: [] },
          { name: "יא", num: "02", dayOfWeek: 1, events: [] },
          { name: "יב", num: "03", dayOfWeek: 2, events: [] },
          { name: "יג", num: "04", dayOfWeek: 3, events: [] },
          { name: "יד", num: "05", dayOfWeek: 4, events: [] },
          { name: "טו", num: "06", dayOfWeek: 5, events: [] },
          { name: "טז", num: "07", dayOfWeek: 6, events: [] },
          { name: "יז", num: "08", dayOfWeek: 7, events: [] },
          { name: "יח", num: "09", dayOfWeek: 1, events: [] },
          { name: "יט", num: "10", dayOfWeek: 2, events: [] },
          { name: "כ", num: "11", dayOfWeek: 3, events: [] },
          { name: "כא", num: "12", dayOfWeek: 4, events: [] },
          { name: "כב", num: "13", dayOfWeek: 5, events: [] },
          { name: "כג", num: "14", dayOfWeek: 6, events: [] },
          { name: "כד", num: "15", dayOfWeek: 7, events: [] },
          { name: "כה", num: "16", dayOfWeek: 1, events: [] },
          { name: "כו", num: "17", dayOfWeek: 2, events: [] },
          { name: "כז", num: "18", dayOfWeek: 3, events: [] },
          { name: "כח", num: "19", dayOfWeek: 4, events: [] },
          { name: "כט", num: "20", dayOfWeek: 5, events: [] },
        ],
      },
      {
        name: "כסלו",
        num: "נובמבר-דצמבר",
        Days: [
          { name: "א", num: "21", dayOfWeek: 6, events: [] },
          { name: "ב", num: "22", dayOfWeek: 7, events: [] },
          { name: "ג", num: "23", dayOfWeek: 1, events: [] },
          { name: "ד", num: "24", dayOfWeek: 2, events: [] },
          { name: "ה", num: "25", dayOfWeek: 3, events: [] },
          { name: "ו", num: "26", dayOfWeek: 4, events: [] },
          { name: "ז", num: "27", dayOfWeek: 5, events: [] },
          { name: "ח", num: "28", dayOfWeek: 6, events: [] },
          { name: "ט", num: "29", dayOfWeek: 7, events: [] },
          { name: "י", num: "30", dayOfWeek: 1, events: [] },
          { name: "יא", num: "01", dayOfWeek: 2, events: [] },
          { name: "יב", num: "02", dayOfWeek: 3, events: [] },
          { name: "יג", num: "03", dayOfWeek: 4, events: [] },
          { name: "יד", num: "04", dayOfWeek: 5, events: [] },
          { name: "טו", num: "05", dayOfWeek: 6, events: [] },
          { name: "טז", num: "06", dayOfWeek: 7, events: [] },
          { name: "יז", num: "07", dayOfWeek: 1, events: [] },
          { name: "יח", num: "08", dayOfWeek: 2, events: [] },
          { name: "יט", num: "09", dayOfWeek: 3, events: [] },
          { name: "כ", num: "10", dayOfWeek: 4, events: [] },
          { name: "כא", num: "11", dayOfWeek: 5, events: [] },
          { name: "כב", num: "12", dayOfWeek: 6, events: [] },
          { name: "כג", num: "13", dayOfWeek: 7, events: [] },
          { name: "כד", num: "14", dayOfWeek: 1, events: [] },
          {
            name: "כה",
            num: "15",
            dayOfWeek: 2,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          {
            name: "כו",
            num: "16",
            dayOfWeek: 3,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          {
            name: "כז",
            num: "17",
            dayOfWeek: 4,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          {
            name: "כח",
            num: "18",
            dayOfWeek: 5,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          {
            name: "כט",
            num: "19",
            dayOfWeek: 6,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          {
            name: "ל",
            num: "20",
            dayOfWeek: 7,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
        ],
      },

      {
        name: "טבת",
        num: "דצמבר-ינואר",
        Days: [
          {
            name: "א",
            num: "21",
            dayOfWeek: 1,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          {
            name: "ב",
            num: "22",
            dayOfWeek: 2,
            events: [{ type: "🕯️", text: "חנוכה" }],
          },
          { name: "ג", num: "23", dayOfWeek: 3, events: [] },
          { name: "ד", num: "24", dayOfWeek: 4, events: [] },
          { name: "ה", num: "25", dayOfWeek: 5, events: [] },
          { name: "ו", num: "26", dayOfWeek: 6, events: [] },
          { name: "ז", num: "27", dayOfWeek: 7, events: [] },
          { name: "ח", num: "28", dayOfWeek: 1, events: [] },
          { name: "ט", num: "29", dayOfWeek: 2, events: [] },
          {
            name: "י",
            num: "30",
            dayOfWeek: 3,
            events: [{ type: "❎", text: "צום עשרה בטבת" }],
          },
          { name: "יא", num: "31", dayOfWeek: 4, events: [] },
          { name: "יב", num: "01", dayOfWeek: 5, events: [] },
          { name: "יג", num: "02", dayOfWeek: 6, events: [] },
          { name: "יד", num: "03", dayOfWeek: 7, events: [] },
          { name: "טו", num: "04", dayOfWeek: 1, events: [] },
          { name: "טז", num: "05", dayOfWeek: 2, events: [] },
          { name: "יז", num: "06", dayOfWeek: 3, events: [] },
          { name: "יח", num: "07", dayOfWeek: 4, events: [] },
          { name: "יט", num: "08", dayOfWeek: 5, events: [] },
          { name: "כ", num: "09", dayOfWeek: 6, events: [] },
          { name: "כא", num: "10", dayOfWeek: 7, events: [] },
          { name: "כב", num: "11", dayOfWeek: 1, events: [] },
          { name: "כג", num: "12", dayOfWeek: 2, events: [] },
          { name: "כד", num: "13", dayOfWeek: 3, events: [] },
          { name: "כה", num: "14", dayOfWeek: 4, events: [] },
          { name: "כו", num: "15", dayOfWeek: 5, events: [] },
          { name: "כז", num: "16", dayOfWeek: 6, events: [] },
          { name: "כח", num: "17", dayOfWeek: 7, events: [] },
          { name: "כט", num: "18", dayOfWeek: 1, events: [] },
        ],
      },
      {
        name: "שבט",
        num: "ינואר-פברואר",
        Days: [
          { name: "א", num: "19", dayOfWeek: 2, events: [] },
          { name: "ב", num: "20", dayOfWeek: 3, events: [] },
          { name: "ג", num: "21", dayOfWeek: 4, events: [] },
          { name: "ד", num: "22", dayOfWeek: 5, events: [] },
          { name: "ה", num: "23", dayOfWeek: 6, events: [] },
          { name: "ו", num: "24", dayOfWeek: 7, events: [] },
          { name: "ז", num: "25", dayOfWeek: 1, events: [] },
          { name: "ח", num: "26", dayOfWeek: 2, events: [] },
          { name: "ט", num: "27", dayOfWeek: 3, events: [] },
          { name: "י", num: "28", dayOfWeek: 4, events: [] },
          { name: "יא", num: "29", dayOfWeek: 5, events: [] },
          { name: "יב", num: "30", dayOfWeek: 6, events: [] },
          { name: "יג", num: "31", dayOfWeek: 7, events: [] },
          { name: "יד", num: "01", dayOfWeek: 1, events: [] },
          {
            name: "טו",
            num: "02",
            dayOfWeek: 2,
            events: [{ type: "🍇", text: "טו בשבט" }],
          },
          { name: "טז", num: "03", dayOfWeek: 3, events: [] },
          { name: "יז", num: "04", dayOfWeek: 4, events: [] },
          { name: "יח", num: "05", dayOfWeek: 5, events: [] },
          { name: "יט", num: "06", dayOfWeek: 6, events: [] },
          { name: "כ", num: "07", dayOfWeek: 7, events: [] },
          { name: "כא", num: "08", dayOfWeek: 1, events: [] },
          { name: "כב", num: "09", dayOfWeek: 2, events: [] },
          { name: "כג", num: "10", dayOfWeek: 3, events: [] },
          { name: "כד", num: "11", dayOfWeek: 4, events: [] },
          { name: "כה", num: "12", dayOfWeek: 5, events: [] },
          { name: "כו", num: "13", dayOfWeek: 6, events: [] },
          { name: "כז", num: "14", dayOfWeek: 7, events: [] },
          { name: "כח", num: "15", dayOfWeek: 1, events: [] },
          { name: "כט", num: "16", dayOfWeek: 2, events: [] },
          { name: "ל", num: "17", dayOfWeek: 3, events: [] },
        ],
      },

      {
        name: "אדר",
        num: "פברואר-מרץ",
        Days: [
          { name: "א", num: "18", dayOfWeek: 4, events: [] },
          { name: "ב", num: "19", dayOfWeek: 5, events: [] },
          { name: "ג", num: "20", dayOfWeek: 6, events: [] },
          { name: "ד", num: "21", dayOfWeek: 7, events: [] },
          { name: "ה", num: "22", dayOfWeek: 1, events: [] },
          { name: "ו", num: "23", dayOfWeek: 2, events: [] },
          { name: "ז", num: "24", dayOfWeek: 3, events: [] },
          { name: "ח", num: "25", dayOfWeek: 4, events: [] },
          { name: "ט", num: "26", dayOfWeek: 5, events: [] },
          { name: "י", num: "27", dayOfWeek: 6, events: [] },
          { name: "יא", num: "28", dayOfWeek: 7, events: [] },
          { name: "יב", num: "01", dayOfWeek: 1, events: [] },
          {
            name: "יג",
            num: "02",
            dayOfWeek: 2,
            events: [{ type: "🤡", text: "פורים דפרזים" }],
          },
          {
            name: "יד",
            num: "03",
            dayOfWeek: 3,
            events: [{ type: "🤡", text: "פורים דמוקפים" }],
          },
          { name: "טו", num: "04", dayOfWeek: 4, events: [] },
          { name: "טז", num: "05", dayOfWeek: 5, events: [] },
          { name: "יז", num: "06", dayOfWeek: 6, events: [] },
          { name: "יח", num: "07", dayOfWeek: 7, events: [] },
          { name: "יט", num: "08", dayOfWeek: 1, events: [] },
          { name: "כ", num: "09", dayOfWeek: 2, events: [] },
          { name: "כא", num: "10", dayOfWeek: 3, events: [] },
          { name: "כב", num: "11", dayOfWeek: 4, events: [] },
          { name: "כג", num: "12", dayOfWeek: 5, events: [] },
          { name: "כד", num: "13", dayOfWeek: 6, events: [] },
          { name: "כה", num: "14", dayOfWeek: 7, events: [] },
          { name: "כו", num: "15", dayOfWeek: 1, events: [] },
          { name: "כז", num: "16", dayOfWeek: 2, events: [] },
          { name: "כח", num: "17", dayOfWeek: 3, events: [] },
          { name: "כט", num: "18", dayOfWeek: 4, events: [] },
        ],
      },
      {
        name: "ניסן",
        num: "מרץ-אפריל",
        Days: [
          { name: "א", num: "19", dayOfWeek: 5, events: [] },
          { name: "ב", num: "20", dayOfWeek: 6, events: [] },
          { name: "ג", num: "21", dayOfWeek: 7, events: [] },
          { name: "ד", num: "22", dayOfWeek: 1, events: [] },
          { name: "ה", num: "23", dayOfWeek: 2, events: [] },
          { name: "ו", num: "24", dayOfWeek: 3, events: [] },
          { name: "ז", num: "25", dayOfWeek: 4, events: [] },
          { name: "ח", num: "26", dayOfWeek: 5, events: [] },
          { name: "ט", num: "27", dayOfWeek: 6, events: [] },
          { name: "י", num: "28", dayOfWeek: 7, events: [] },
          { name: "יא", num: "29", dayOfWeek: 1, events: [] },
          { name: "יב", num: "30", dayOfWeek: 2, events: [] },
          { name: "יג", num: "31", dayOfWeek: 3, events: [] },
          { name: "יד", num: "01", dayOfWeek: 4, events: [] },
          {
            name: "טו",
            num: "02",
            dayOfWeek: 5,
            events: [{ type: "🥬", text: "יום טוב פסח" }],
          },
          {
            name: "טז",
            num: "03",
            dayOfWeek: 6,
            events: [{ type: "🥬", text: "א דחול המועד" }],
          },
          {
            name: "יז",
            num: "04",
            dayOfWeek: 7,
            events: [{ type: "🥬", text: "ב דחול המועד" }],
          },
          {
            name: "יח",
            num: "05",
            dayOfWeek: 1,
            events: [{ type: "🥬", text: "ג דחול המועד" }],
          },
          {
            name: "יט",
            num: "06",
            dayOfWeek: 2,
            events: [{ type: "🥬", text: "ד דחול המועד" }],
          },
          {
            name: "כ",
            num: "07",
            dayOfWeek: 3,
            events: [{ type: "🥬", text: "ה דחול המועד" }],
          },
          {
            name: "כא",
            num: "08",
            dayOfWeek: 4,
            events: [{ type: "🥬", text: "שביעי של פסח" }],
          },
          { name: "כב", num: "09", dayOfWeek: 5, events: [] },
          { name: "כג", num: "10", dayOfWeek: 6, events: [] },
          { name: "כד", num: "11", dayOfWeek: 7, events: [] },
          { name: "כה", num: "12", dayOfWeek: 1, events: [] },
          { name: "כו", num: "13", dayOfWeek: 2, events: [] },
          { name: "כז", num: "14", dayOfWeek: 3, events: [] },
          { name: "כח", num: "15", dayOfWeek: 4, events: [] },
          { name: "כט", num: "16", dayOfWeek: 5, events: [] },
          { name: "ל", num: "17", dayOfWeek: 6, events: [] },
        ],
      },

      {
        name: "אייר",
        num: "אפריל-מאי",
        Days: [
          { name: "א", num: "18", dayOfWeek: 7, events: [] },
          { name: "ב", num: "19", dayOfWeek: 1, events: [] },
          { name: "ג", num: "20", dayOfWeek: 2, events: [] },
          { name: "ד", num: "21", dayOfWeek: 3, events: [] },
          { name: "ה", num: "22", dayOfWeek: 4, events: [] },
          { name: "ו", num: "23", dayOfWeek: 5, events: [] },
          { name: "ז", num: "24", dayOfWeek: 6, events: [] },
          { name: "ח", num: "25", dayOfWeek: 7, events: [] },
          { name: "ט", num: "26", dayOfWeek: 1, events: [] },
          { name: "י", num: "27", dayOfWeek: 2, events: [] },
          { name: "יא", num: "28", dayOfWeek: 3, events: [] },
          { name: "יב", num: "29", dayOfWeek: 4, events: [] },
          { name: "יג", num: "30", dayOfWeek: 5, events: [] },
          { name: "יד", num: "01", dayOfWeek: 6, events: [] },
          { name: "טו", num: "02", dayOfWeek: 7, events: [] },
          { name: "טז", num: "03", dayOfWeek: 1, events: [] },
          { name: "יז", num: "04", dayOfWeek: 2, events: [] },
          {
            name: "יח",
            num: "05",
            dayOfWeek: 3,
            events: [{ type: "🔥", text: "לג בעומר" }],
          },
          { name: "יט", num: "06", dayOfWeek: 4, events: [] },
          { name: "כ", num: "07", dayOfWeek: 5, events: [] },
          { name: "כא", num: "08", dayOfWeek: 6, events: [] },
          { name: "כב", num: "09", dayOfWeek: 7, events: [] },
          { name: "כג", num: "10", dayOfWeek: 1, events: [] },
          { name: "כד", num: "11", dayOfWeek: 2, events: [] },
          { name: "כה", num: "12", dayOfWeek: 3, events: [] },
          { name: "כו", num: "13", dayOfWeek: 4, events: [] },
          { name: "כז", num: "14", dayOfWeek: 5, events: [] },
          { name: "כח", num: "15", dayOfWeek: 6, events: [] },
          { name: "כט", num: "16", dayOfWeek: 7, events: [] },
        ],
      },
      {
        name: "סיוון",
        num: "מאי-יוני",
        Days: [
          { name: "א", num: "17", dayOfWeek: 1, events: [] },
          { name: "ב", num: "18", dayOfWeek: 2, events: [] },
          { name: "ג", num: "19", dayOfWeek: 3, events: [] },
          { name: "ד", num: "20", dayOfWeek: 4, events: [] },
          { name: "ה", num: "21", dayOfWeek: 5, events: [] },
          {
            name: "ו",
            num: "22",
            dayOfWeek: 6,
            events: [{ type: "📖", text: "יום טוב שבועות" }],
          },
          { name: "ז", num: "23", dayOfWeek: 7, events: [] },
          { name: "ח", num: "24", dayOfWeek: 1, events: [] },
          { name: "ט", num: "25", dayOfWeek: 2, events: [] },
          { name: "י", num: "26", dayOfWeek: 3, events: [] },
          { name: "יא", num: "27", dayOfWeek: 4, events: [] },
          { name: "יב", num: "28", dayOfWeek: 5, events: [] },
          { name: "יג", num: "29", dayOfWeek: 6, events: [] },
          { name: "יד", num: "30", dayOfWeek: 7, events: [] },
          { name: "טו", num: "31", dayOfWeek: 1, events: [] },
          { name: "טז", num: "01", dayOfWeek: 2, events: [] },
          { name: "יז", num: "02", dayOfWeek: 3, events: [] },
          { name: "יח", num: "03", dayOfWeek: 4, events: [] },
          { name: "יט", num: "04", dayOfWeek: 5, events: [] },
          { name: "כ", num: "05", dayOfWeek: 6, events: [] },
          { name: "כא", num: "06", dayOfWeek: 7, events: [] },
          { name: "כב", num: "07", dayOfWeek: 1, events: [] },
          { name: "כג", num: "08", dayOfWeek: 2, events: [] },
          { name: "כד", num: "09", dayOfWeek: 3, events: [] },
          { name: "כה", num: "10", dayOfWeek: 4, events: [] },
          { name: "כו", num: "11", dayOfWeek: 5, events: [] },
          { name: "כז", num: "12", dayOfWeek: 6, events: [] },
          { name: "כח", num: "13", dayOfWeek: 7, events: [] },
          { name: "כט", num: "14", dayOfWeek: 1, events: [] },
          { name: "ל", num: "15", dayOfWeek: 2, events: [] },
        ],
      },

      {
        name: "תמוז",
        num: "יוני-יולי",
        Days: [
          { name: "א", num: "16", dayOfWeek: 3, events: [] },
          { name: "ב", num: "17", dayOfWeek: 4, events: [] },
          { name: "ג", num: "18", dayOfWeek: 5, events: [] },
          { name: "ד", num: "19", dayOfWeek: 6, events: [] },
          { name: "ה", num: "20", dayOfWeek: 7, events: [] },
          { name: "ו", num: "21", dayOfWeek: 1, events: [] },
          { name: "ז", num: "22", dayOfWeek: 2, events: [] },
          { name: "ח", num: "23", dayOfWeek: 3, events: [] },
          { name: "ט", num: "24", dayOfWeek: 4, events: [] },
          { name: "י", num: "25", dayOfWeek: 5, events: [] },
          { name: "יא", num: "26", dayOfWeek: 6, events: [] },
          { name: "יב", num: "27", dayOfWeek: 7, events: [] },
          { name: "יג", num: "28", dayOfWeek: 1, events: [] },
          { name: "יד", num: "29", dayOfWeek: 2, events: [] },
          { name: "טו", num: "30", dayOfWeek: 3, events: [] },
          { name: "טז", num: "01", dayOfWeek: 4, events: [] },
          {
            name: "יז",
            num: " 02",
            dayOfWeek: 5,
            events: [{ type: "❎", text: "צום שבעה עשר בתמוז" }],
          },
          { name: "יח", num: "03", dayOfWeek: 6, events: [] },
          { name: "יט", num: "04", dayOfWeek: 7, events: [] },
          { name: "כ", num: "05", dayOfWeek: 1, events: [] },
          { name: "כא", num: "06", dayOfWeek: 2, events: [] },
          { name: "כב", num: "07", dayOfWeek: 3, events: [] },
          { name: "כג", num: "08", dayOfWeek: 4, events: [] },
          { name: "כד", num: "09", dayOfWeek: 5, events: [] },
          { name: "כה", num: "10", dayOfWeek: 6, events: [] },
          { name: "כו", num: "11", dayOfWeek: 7, events: [] },
          { name: "כז", num: "12", dayOfWeek: 1, events: [] },
          { name: "כח", num: "13", dayOfWeek: 2, events: [] },
          { name: "כט", num: "14", dayOfWeek: 3, events: [] },
        ],
      },
      {
        name: "אב",
        num: "יולי-אוגוסט",
        Days: [
          { name: "א", num: "15", dayOfWeek: 4, events: [] },
          { name: "ב", num: "16", dayOfWeek: 5, events: [] },
          { name: "ג", num: "17", dayOfWeek: 6, events: [] },
          { name: "ד", num: "18", dayOfWeek: 7, events: [] },
          { name: "ה", num: "19", dayOfWeek: 1, events: [] },
          { name: "ו", num: "20", dayOfWeek: 2, events: [] },
          { name: "ז", num: "21", dayOfWeek: 3, events: [] },
          { name: "ח", num: "22", dayOfWeek: 4, events: [] },
          {
            name: "ט",
            num: "23",
            dayOfWeek: 5,
            events: [{ type: "❎", text: "צום תשעה באב" }],
          },
          { name: "י", num: "24", dayOfWeek: 6, events: [] },
          { name: "יא", num: "25", dayOfWeek: 7, events: [] },
          { name: "יב", num: "26", dayOfWeek: 1, events: [] },
          { name: "יג", num: "27", dayOfWeek: 2, events: [] },
          { name: "יד", num: "28", dayOfWeek: 3, events: [] },
          { name: "טו", num: "29", dayOfWeek: 4, events: [] },
          { name: "טז", num: "30", dayOfWeek: 5, events: [] },
          { name: "יז", num: "31", dayOfWeek: 6, events: [] },
          { name: "יח", num: "01", dayOfWeek: 7, events: [] },
          { name: "יט", num: "02", dayOfWeek: 1, events: [] },
          { name: "כ", num: "03", dayOfWeek: 2, events: [] },
          { name: "כא", num: "04", dayOfWeek: 3, events: [] },
          { name: "כב", num: "05", dayOfWeek: 4, events: [] },
          { name: "כג", num: "06", dayOfWeek: 5, events: [] },
          { name: "כד", num: "07", dayOfWeek: 6, events: [] },
          { name: "כה", num: "08", dayOfWeek: 7, events: [] },
          { name: "כו", num: "09", dayOfWeek: 1, events: [] },
          { name: "כז", num: "10", dayOfWeek: 2, events: [] },
          { name: "כח", num: "11", dayOfWeek: 3, events: [] },
          { name: "כט", num: "12", dayOfWeek: 4, events: [] },
          { name: "ל", num: "13", dayOfWeek: 5, events: [] },
        ],
      },

      {
        name: "אלול",
        num: "אוגוסט-ספטמבר",
        Days: [
          { name: "א", num: "14", dayOfWeek: 6, events: [] },
          { name: "ב", num: "15", dayOfWeek: 7, events: [] },
          { name: "ג", num: "16", dayOfWeek: 1, events: [] },
          { name: "ד", num: "17", dayOfWeek: 2, events: [] },
          { name: "ה", num: "18", dayOfWeek: 3, events: [] },
          { name: "ו", num: "19", dayOfWeek: 4, events: [] },
          { name: "ז", num: "20", dayOfWeek: 5, events: [] },
          { name: "ח", num: "21", dayOfWeek: 6, events: [] },
          { name: "ט", num: "22", dayOfWeek: 7, events: [] },
          { name: "י", num: "23", dayOfWeek: 1, events: [] },
          { name: "יא", num: "24", dayOfWeek: 2, events: [] },
          { name: "יב", num: "25", dayOfWeek: 3, events: [] },
          { name: "יג", num: "26", dayOfWeek: 4, events: [] },
          { name: "יד", num: "27", dayOfWeek: 5, events: [] },
          { name: "טו", num: "28", dayOfWeek: 6, events: [] },
          { name: "טז", num: "29", dayOfWeek: 7, events: [] },
          { name: "יז", num: "30", dayOfWeek: 1, events: [] },
          { name: "יח", num: "31", dayOfWeek: 2, events: [] },
          { name: "יט", num: "01", dayOfWeek: 3, events: [] },
          { name: "כ", num: "02", dayOfWeek: 4, events: [] },
          { name: "כא", num: "03", dayOfWeek: 5, events: [] },
          { name: "כב", num: "04", dayOfWeek: 6, events: [] },
          { name: "כג", num: "05", dayOfWeek: 7, events: [] },
          { name: "כד", num: "06", dayOfWeek: 1, events: [] },
          { name: "כה", num: "07", dayOfWeek: 2, events: [] },
          { name: "כו", num: "08", dayOfWeek: 3, events: [] },
          { name: "כז", num: "09", dayOfWeek: 4, events: [] },
          { name: "כח", num: "10", dayOfWeek: 5, events: [] },
          { name: "כט", num: "11", dayOfWeek: 6, events: [] },
        ],
      },
    ],
  });

  const create = () => {
    setCounter(10)
    window.localStorage.setItem("counter", window.localStorage.getItem('counter') + 1)
    steFlag(true)
    window.localStorage.setItem(name, JSON.stringify(basicCalender))
  }

  return (
    <>
      {!flag ?
        <Form
          mysetName={setName}
          mysetFont={setFont}
          mysetBackRound={setBackRound}
          create={create}
          counter={counter}
          setBasicCalender={setBasicCalender}
          steFlag={steFlag}
        ></Form>

        :
        <div>

          <Form
            mysetName={setName}
            mysetFont={setFont}
            mysetBackRound={setBackRound}
            flug={true}
            counter={counter}
            setBasicCalender={setBasicCalender}
          ></Form>

          <Calander
            myName={name}
            myFont={font}
            myBackRound={backRound}
            basicCalender={basicCalender}
          ></Calander>
          <AddEvent
            basicCalender={basicCalender}
            setBasicCalender={setBasicCalender}
            name={name}
          ></AddEvent>
        </div>
      }
    </>
  );
};
